// Auto-generated by deploy.js — do not edit manually
export const CONTRACT_ADDRESSES = {
  "ArenaToken": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  "CreatureNFT": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
  "BattleEngine": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
  "Marketplace": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
  "TournamentManager": "0x0165878A594ca255338adfa4d48449f69242Eb8F",
  "Treasury": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  "ReputationSystem": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
  "GameItems": "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
  "Escrow": "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
  "DisputeResolution": "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318"
};

export const CHAIN_CONFIG = {
  chainId: 31337,
  name: "localhost",
  rpcUrl: "http://127.0.0.1:8545",
};

export const ELEMENT_NAMES  = ["Fire", "Water", "Earth", "Air", "Light", "Dark"];
export const RARITY_NAMES   = ["Common", "Uncommon", "Rare", "Legendary"];
export const RARITY_COLORS  = ["#9ca3af", "#4ade80", "#60a5fa", "#f59e0b"];
export const ELEMENT_EMOJIS = ["🔥", "💧", "🌍", "🌪️", "✨", "🌑"];
export const ELEMENT_CLASSES = ["el-fire", "el-water", "el-earth", "el-air", "el-light", "el-dark"];

export const ITEM_NAMES   = ["XP Potion", "Breed Boost", "Battle Boost"];
export const ITEM_EMOJIS  = ["⚗️", "🧬", "⚡"];
export const ITEM_DESCS   = [
  "Instantly grants 100 XP to a creature",
  "Grants 200 XP — simulate offspring bonus",
  "Grants 50 XP + records an extra win",
];
